/**
 * Recma (ESTree) plugin that removes inlined component names from the
 * `props.components` destructuring generated by @mdx-js/mdx.
 *
 * When remarkExtractLocalImports inlines a local component (e.g. MemberCard),
 * the MDX compiler still generates:
 *
 *   const {Deck, MemberCard, Slide} = props.components || {};
 *   if (!MemberCard) _missingMdxReference("MemberCard", true);
 *
 * This plugin removes MemberCard from the destructuring pattern and removes
 * the corresponding _missingMdxReference check, so the inlined top-level
 * definition is used instead.
 *
 * The list of inlined names is passed via vfile.data.inlinedComponentNames,
 * set by remarkExtractLocalImports.
 */

interface EstreeNode {
  type: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [key: string]: any;
}

interface VFile {
  data: Record<string, unknown>;
}

export function recmaExcludeInlinedComponents() {
  return (tree: EstreeNode, file: VFile) => {
    const inlinedNames = file.data.inlinedComponentNames as string[] | undefined;
    if (!inlinedNames || inlinedNames.length === 0) return;

    const nameSet = new Set(inlinedNames);
    walkProgram(tree, nameSet);
  };
}

function walkProgram(node: EstreeNode, names: Set<string>) {
  if (node.body && Array.isArray(node.body)) {
    walkBody(node.body, names);
  }
}

function walkBody(body: EstreeNode[], names: Set<string>) {
  for (let i = body.length - 1; i >= 0; i--) {
    const stmt = body[i];

    // Remove: if (!MemberCard) _missingMdxReference("MemberCard", true);
    if (isMissingRefCheck(stmt, names)) {
      body.splice(i, 1);
      continue;
    }

    // Clean destructuring: const {Deck, MemberCard, Slide} = props.components || {}
    if (stmt.type === "VariableDeclaration" && stmt.declarations) {
      for (const decl of stmt.declarations) {
        if (decl.id?.type === "ObjectPattern" && isComponentsDestructuring(decl)) {
          cleanDestructuringPattern(decl.id, names);
        }
      }
    }

    // Recurse into function bodies (where _createMdxContent lives)
    if (stmt.type === "FunctionDeclaration" && stmt.body?.body) {
      walkBody(stmt.body.body, names);
    }

    // Also handle ExpressionStatement wrapping function expressions
    if (stmt.type === "ExpressionStatement") {
      walkExpression(stmt.expression, names);
    }

    // VariableDeclaration with function expression init
    if (stmt.type === "VariableDeclaration" && stmt.declarations) {
      for (const decl of stmt.declarations) {
        if (decl.init) walkExpression(decl.init, names);
      }
    }
  }
}

function walkExpression(expr: EstreeNode, names: Set<string>) {
  if (!expr) return;
  if (
    (expr.type === "FunctionExpression" || expr.type === "ArrowFunctionExpression") &&
    expr.body?.body
  ) {
    walkBody(expr.body.body, names);
  }
  if (expr.type === "CallExpression") {
    walkExpression(expr.callee, names);
    if (expr.arguments) {
      for (const arg of expr.arguments) {
        walkExpression(arg, names);
      }
    }
  }
  if (expr.type === "AssignmentExpression") {
    walkExpression(expr.right, names);
  }
}

/**
 * Check if a statement is: if (!MemberCard) _missingMdxReference("MemberCard", true)
 */
function isMissingRefCheck(stmt: EstreeNode, names: Set<string>): boolean {
  if (stmt.type !== "IfStatement") return false;
  // test: !MemberCard (UnaryExpression with ! and Identifier)
  const test = stmt.test;
  if (test?.type !== "UnaryExpression" || test.operator !== "!") return false;
  if (test.argument?.type !== "Identifier") return false;
  if (!names.has(test.argument.name)) return false;

  // consequent should contain _missingMdxReference call
  const consequent = stmt.consequent;
  if (consequent?.type === "ExpressionStatement") {
    const expr = consequent.expression;
    if (expr?.type === "CallExpression" && expr.callee?.name === "_missingMdxReference") {
      return true;
    }
  }
  return false;
}

/**
 * Check if a variable declarator is destructuring from props.components
 * Pattern: const {...} = _components or const {...} = props.components || {}
 */
function isComponentsDestructuring(decl: EstreeNode): boolean {
  const init = decl.init;
  if (!init) return false;

  // Direct: _components (identifier starting with underscore or named _components)
  if (init.type === "Identifier" && init.name === "_components") return true;

  // LogicalExpression: props.components || {}
  if (init.type === "LogicalExpression") {
    const left = init.left;
    if (left?.type === "MemberExpression") {
      if (left.property?.name === "components" || left.property?.value === "components") {
        return true;
      }
    }
  }

  return false;
}

/**
 * Remove inlined component names from an ObjectPattern.
 * e.g. { Deck, MemberCard, Slide } → { Deck, Slide }
 */
function cleanDestructuringPattern(pattern: EstreeNode, names: Set<string>): void {
  if (!pattern.properties || !Array.isArray(pattern.properties)) return;
  pattern.properties = pattern.properties.filter((prop: EstreeNode) => {
    // ObjectPattern property: { key: Identifier, value: Identifier }
    const keyName = prop.key?.name ?? prop.key?.value;
    return !names.has(keyName);
  });
}
