import { useEffect, useId, useRef, useState } from "react";

export interface MermaidProps {
  /** Mermaid diagram code */
  children: string;
}

/**
 * Renders a Mermaid diagram.
 *
 * Usage in MDX:
 * ```mdx
 * <Mermaid>
 * graph TD
 *   A --> B
 * </Mermaid>
 * ```
 *
 * The mermaid library is dynamically imported on the client side,
 * so it does not need to be installed as a project dependency.
 */
export function Mermaid({ children }: MermaidProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [svg, setSvg] = useState<string>("");
  const [error, setError] = useState<string>("");
  const id = useId().replace(/:/g, "_");

  useEffect(() => {
    let cancelled = false;

    async function render() {
      try {
        // @ts-expect-error mermaid is an optional peer dependency
        const mermaid = await import("mermaid");
        mermaid.default.initialize({
          startOnLoad: false,
          theme: "default",
          securityLevel: "loose",
        });

        const code = typeof children === "string" ? children.trim() : "";
        if (!code) return;

        const { svg: rendered } = await mermaid.default.render(`mermaid-${id}`, code);

        if (!cancelled) {
          setSvg(rendered);
          setError("");
        }
      } catch (err) {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : "Failed to render diagram");
        }
      }
    }

    void render();
    return () => {
      cancelled = true;
    };
  }, [children, id]);

  if (error) {
    return (
      <div className="reslide-mermaid reslide-mermaid--error">
        <pre>{error}</pre>
      </div>
    );
  }

  // SVG content is generated by the mermaid library itself (not user-supplied HTML),
  // so dangerouslySetInnerHTML is safe here.
  return (
    <div ref={containerRef} className="reslide-mermaid" dangerouslySetInnerHTML={{ __html: svg }} />
  );
}
