import { isValidElement, useEffect, useId, useRef, useState } from "react";
import type { ReactNode } from "react";

export interface MermaidProps {
  /** Mermaid diagram code (string or MDX children) */
  children: ReactNode;
}

/**
 * Recursively extract text content from React children.
 * MDX wraps raw text in paragraphs and other elements,
 * so we need to traverse the tree to get the original text.
 */
function extractText(node: ReactNode): string {
  if (node == null || typeof node === "boolean") return "";
  if (typeof node === "string") return node;
  if (typeof node === "number") return String(node);
  if (Array.isArray(node)) return node.map(extractText).join("");
  if (isValidElement(node)) {
    const { children } = node.props as { children?: ReactNode };
    const text = extractText(children);
    // MDX wraps lines in <p>, restore line breaks between block elements
    const tag = typeof node.type === "string" ? node.type : "";
    if (tag === "p" || tag === "br") return `${text}\n`;
    return text;
  }
  return "";
}

/**
 * Renders a Mermaid diagram.
 *
 * Usage in MDX:
 * ```mdx
 * <Mermaid>
 * graph TD
 *   A --> B
 * </Mermaid>
 * ```
 *
 * The mermaid library is dynamically imported on the client side,
 * so it does not need to be installed as a project dependency.
 */
export function Mermaid({ children }: MermaidProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [svg, setSvg] = useState<string>("");
  const [error, setError] = useState<string>("");
  const id = useId().replace(/:/g, "_");

  const code = extractText(children).trim();

  useEffect(() => {
    if (!code) return;

    let cancelled = false;

    async function render() {
      try {
        // Dynamic import with variable to bypass Vite's static import analysis.
        // mermaid is an optional peer dependency — consumers must install it.
        const pkg = "mermaid";
        const mermaid = await import(/* @vite-ignore */ pkg);
        mermaid.default.initialize({
          startOnLoad: false,
          theme: "default",
          securityLevel: "loose",
        });

        const { svg: rendered } = await mermaid.default.render(`mermaid-${id}`, code);

        if (!cancelled) {
          setSvg(rendered);
          setError("");
        }
      } catch (err) {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : "Failed to render diagram");
        }
      }
    }

    void render();
    return () => {
      cancelled = true;
    };
  }, [code, id]);

  if (error) {
    return (
      <div className="reslide-mermaid reslide-mermaid--error">
        <pre>{error}</pre>
      </div>
    );
  }

  // SVG content is generated by the mermaid library itself (not user-supplied HTML),
  // so dangerouslySetInnerHTML is safe here.
  return (
    <div ref={containerRef} className="reslide-mermaid" dangerouslySetInnerHTML={{ __html: svg }} />
  );
}
